import { NextRequest, NextResponse } from 'next/server';
import { google } from 'googleapis';
import { Readable } from 'stream';

export async function POST(request: NextRequest) {
    try {
        // Validate environment variables first
        const requiredEnvVars = [
            'GOOGLE_DRIVE_CLIENT_ID',
            'GOOGLE_DRIVE_CLIENT_SECRET',
            'GOOGLE_DRIVE_REDIRECT_URI',
            'GOOGLE_DRIVE_REFRESH_TOKEN',
            'GOOGLE_DRIVE_FOLDER_ID'
        ];

        const missingVars = requiredEnvVars.filter(varName => !process.env[varName]);
        if (missingVars.length > 0) {
            console.error('Missing environment variables:', missingVars);
            return NextResponse.json(
                { error: `Server configuration error: Missing ${missingVars.join(', ')}` },
                { status: 500 }
            );
        }

        const formData = await request.formData();
        const file = formData.get('file') as File;
        const submissionId = formData.get('submissionId') as string;
        const userId = formData.get('userId') as string;

        if (!file) {
            return NextResponse.json({ error: 'No file provided' }, { status: 400 });
        }

        console.log(`[Upload] Starting upload for submission ${submissionId}, user ${userId}`);

        // Configure Google Drive OAuth2 client
        const oauth2Client = new google.auth.OAuth2(
            process.env.GOOGLE_DRIVE_CLIENT_ID,
            process.env.GOOGLE_DRIVE_CLIENT_SECRET,
            process.env.GOOGLE_DRIVE_REDIRECT_URI
        );

        oauth2Client.setCredentials({
            refresh_token: process.env.GOOGLE_DRIVE_REFRESH_TOKEN,
        });

        // Try to get access token to verify credentials work
        try {
            await oauth2Client.getAccessToken();
        } catch (tokenError: any) {
            console.error('[Upload] OAuth token error:', tokenError.message);

            if (tokenError.message?.includes('invalid_grant') || tokenError.message?.includes('Invalid claim')) {
                return NextResponse.json(
                    {
                        error: 'Google Drive authentication failed. The refresh token may have expired. Please contact the administrator to regenerate the OAuth token.'
                    },
                    { status: 401 }
                );
            }
            throw tokenError;
        }

        const drive = google.drive({ version: 'v3', auth: oauth2Client });

        // Convert file to buffer
        const bytes = await file.arrayBuffer();
        const buffer = Buffer.from(bytes);

        console.log(`[Upload] File size: ${(buffer.length / 1024).toFixed(2)} KB`);

        // Create file metadata
        const fileMetadata = {
            name: `${submissionId}_${file.name}`,
            parents: [process.env.GOOGLE_DRIVE_FOLDER_ID!],
        };

        const media = {
            mimeType: file.type,
            body: Readable.from(buffer),
        };

        // Upload file to Google Drive
        console.log(`[Upload] Uploading to Google Drive...`);
        const response = await drive.files.create({
            requestBody: fileMetadata,
            media: media,
            fields: 'id, webViewLink, webContentLink',
        });

        console.log(`[Upload] File uploaded successfully, ID: ${response.data.id}`);

        // Make the file publicly accessible
        await drive.permissions.create({
            fileId: response.data.id!,
            requestBody: {
                role: 'reader',
                type: 'anyone',
            },
        });

        // Get the file's public URL
        const fileUrl = `https://drive.google.com/uc?export=view&id=${response.data.id}`;

        console.log(`[Upload] Upload complete for submission ${submissionId}`);

        return NextResponse.json({
            success: true,
            fileId: response.data.id,
            fileUrl: fileUrl,
            webViewLink: response.data.webViewLink,
        });

    } catch (error: any) {
        console.error('[Upload] Google Drive upload error:', {
            message: error.message,
            code: error.code,
            errors: error.errors,
            stack: error.stack
        });

        // Provide specific error messages based on error type
        let errorMessage = 'Failed to upload to Google Drive';
        let statusCode = 500;

        if (error.code === 401 || error.message?.includes('invalid_grant') || error.message?.includes('Invalid claim')) {
            errorMessage = 'Google Drive authentication failed. The refresh token has expired and needs to be regenerated by the administrator.';
            statusCode = 401;
        } else if (error.code === 403) {
            errorMessage = 'Permission denied. The Google Drive folder may not be accessible or the credentials lack required permissions.';
            statusCode = 403;
        } else if (error.code === 404) {
            errorMessage = 'Google Drive folder not found. Please verify the folder ID is correct.';
            statusCode = 404;
        } else if (error.message) {
            errorMessage = `Upload failed: ${error.message}`;
        }

        return NextResponse.json(
            { error: errorMessage },
            { status: statusCode }
        );
    }
}
